### ISSUE TITLE
What's the status on this project?

### ISSUE THREAD

**Issue by JensGM** [LucentFlux/wasm-gpu#1]
Hey,

What is the status on this project? Is it completed, in-development, og maintained? 

Jens

**Comment by Joeoc2001** [comment]
Hi Jens,

This project is an MVP demo - it supports the 1.0 instruction set of WebAssembly, and is complete within that sense. 

Currently it isn't being actively worked on, as the larger project that it was going to form a part of had to be shelved. I am hopeful that I will be able to find another use for it, but for now I don't have the bandwidth to polish it into what I'd like it to someday be.

Hope that makes sense,
Joe
